// unsaved.v

// Generated using ACDS version 21.1 842

`timescale 1 ps / 1 ps
module unsaved (
		input  wire  clk_clk,                           //                     clk.clk
		input  wire  onchip_memory2_0_reset1_reset,     // onchip_memory2_0_reset1.reset
		input  wire  onchip_memory2_0_reset1_reset_req, //                        .reset_req
		input  wire  reset_reset_n                      //                   reset.reset_n
	);

	unsaved_onchip_memory2_0 onchip_memory2_0 (
		.clk        (clk_clk),                           //   clk1.clk
		.address    (),                                  //     s1.address
		.clken      (),                                  //       .clken
		.chipselect (),                                  //       .chipselect
		.write      (),                                  //       .write
		.readdata   (),                                  //       .readdata
		.writedata  (),                                  //       .writedata
		.byteenable (),                                  //       .byteenable
		.reset      (onchip_memory2_0_reset1_reset),     // reset1.reset
		.reset_req  (onchip_memory2_0_reset1_reset_req), //       .reset_req
		.freeze     (1'b0)                               // (terminated)
	);

endmodule
